version: "3"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=personal@demirse.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - web

  web:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.game.rule=Host(`test.demirse.com`)"
      - "traefik.http.routers.game.entrypoints=websecure"
      - "traefik.http.routers.game.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    driver: bridge 